version: '2'

networks:
  default:
#    external:
#      name: dohlestr_default
    ipam:
      config:
        - subnet: 172.20.5.0/24

services:
    workspace:
#        build:
#            args:
#                - INSTALL_SOAP=true
#                - INSTALL_SNMP=true
        env_file: '../.env'
        networks:
          default:
            ipv4_address: 172.20.5.22

    php-fpm:
#      build:
#            args:
#                - INSTALL_MEMCACHED=true
      env_file: '../.env'

    nginx:
        networks:
          default:
            ipv4_address: 172.20.5.80
